// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  DivBlock = 2,
  DivOpenTag = 3,
  DivOpen = 4,
  AttrList = 5,
  Attr = 6,
  AttrName = 7,
  Equals = 8,
  AttrValue = 9,
  TagEnd = 10,
  DivClose = 11,
  Text = 12
