// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#`QVQPOOO_QPO'#C_OgQPO'#C^OOQO'#Cn'#CnOOQO'#Ci'#CiQVQPOOOrQPO'#CbOOQO'#Cj'#CjOwQPO'#CaO!PQPO,58yOOQO,58x,58xO!UQPO,58xOOQO-E6g-E6gO!aQPO,58|OOQO-E6h-E6hOOQO1G.e1G.eOOQO1G.d1G.dOOQO1G.h1G.h",
  stateData: "!p~OaOS~OSPO[RO~OVUOYTP~OSPOZYO[RO~OW]O~OVUOYTX~OY_O~OSPOZ`O[RO~OXaO~OSZYXVW[aV~",
  goto: "!_cPPdjPpsPPPPPPw!RPPP!XXROQTZXQOQTZRXPTVPWQTOQZQT[TZQWPR^WXSOQTZ",
  nodeNames: "⚠ Document DivBlock DivOpenTag DivOpen AttrList Attr AttrName Equals AttrValue TagEnd DivClose Text",
  maxTerm: 18,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: ")m~RgOX!jXY#[YZ#[Z]!j]^#[^p!jpq#[qr!jrs#ms}!j}!O%_!O!_!j!_!`&[!`!c!j!c!}%_!}#O&x#O#P!j#P#Q(_#Q#T!j#T#o%_#o;'S!j;'S;=`#U<%lO!j~!oV[~OX!jZ]!j^p!jq!}!j#O;'S!j;'S;=`#U<%lO!j~#XP;=`<%l!j~#aSa~XY#[YZ#[]^#[pq#[~#rZ[~OX!jZ]!j^p!jqr!jrs$es!}!j#O#Q!j#Q#R#m#R;'S!j;'S;=`#U<%lO!j~$lZX~[~OX!jZ]!j^p!jqr!jrs$es!}!j#O#Q!j#Q#R#m#R;'S!j;'S;=`#U<%lO!j~%f[V~[~OX!jZ]!j^p!jq}!j}!O%_!O!c!j!c!}%_#O#T!j#T#o%_#o;'S!j;'S;=`#U<%lO!j~&cVW~[~OX!jZ]!j^p!jq!}!j#O;'S!j;'S;=`#U<%lO!j~&{P!}#O'O~'RQ!P!Q'X#W#X'|~'[P#W#X'_~'bP#]#^'e~'hP#j#k'k~'nP#P#Q'q~'tP#P#Q'w~'|OZ~~(PP#]#^(S~(VP#j#k(Y~(_OS~~(dX[~OX!jZ]!j^p!jq!}!j#O#P!j#P#Q)P#Q;'S!j;'S;=`#U<%lO!j~)WVY~[~OX!jZ]!j^p!jq!}!j#O;'S!j;'S;=`#U<%lO!j",
  tokenizers: [0],
  topRules: {"Document":[0,1]},
  tokenPrec: 68
})
